import { FileText, User, ShieldCheck, Bot, Link2, CheckCircle, CreditCard, Lock, Scale, Server, AlertTriangle, XCircle, Bell, Gavel, Mail } from "lucide-react";

const sections = [
  {
    icon: FileText,
    title: "1. Acceptance of Terms",
    content: 'By accessing or using ARIA at aria.hoversight.agency ("the Platform"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree to these Terms, do not use the Platform. ARIA is operated by Hoversight ("we", "our", "us"). For questions about these Terms, contact us at accounts@zillamedia.co.',
  },
  {
    icon: Bot,
    title: "2. Description of Service",
    content: "ARIA is an AI-powered marketing platform that provides developer founders with autonomous AI agents for content creation, email marketing, social media management, and advertising strategy. The platform generates marketing content, manages campaigns, and executes approved marketing actions on your behalf through connected third-party services.",
  },
  {
    icon: User,
    title: "3. Account Registration",
    items: [
      "You must provide accurate and complete information when creating an account",
      "You are responsible for maintaining the confidentiality of your account credentials",
      "You are responsible for all activities that occur under your account",
      "You must be at least 18 years old to use ARIA",
      "One person or legal entity may not maintain more than one account",
    ],
  },
  {
    icon: ShieldCheck,
    title: "4. Acceptable Use",
    content: "You agree not to use ARIA to:",
    items: [
      "Generate spam, misleading, or fraudulent content",
      "Violate any applicable laws or regulations",
      "Infringe on intellectual property rights of others",
      "Harass, abuse, or harm other individuals",
      "Distribute malware or engage in phishing",
      "Attempt to gain unauthorized access to the Platform or other users' accounts",
      "Use the Platform for illegal marketing practices",
      "Scrape, crawl, or use automated means to access the Platform beyond the provided API",
      "Reverse engineer or attempt to extract source code from the Platform",
    ],
  },
  {
    icon: Bot,
    title: "5. AI-Generated Content",
    items: [
      "Content generated by ARIA's AI agents is provided as suggestions and drafts",
      "You are responsible for reviewing all generated content before publishing or sending",
      "ARIA does not guarantee the accuracy, quality, or appropriateness of AI-generated content",
      "You retain ownership of content generated for your business, subject to our license below",
      "We do not claim ownership of your business data, generated content, or marketing materials",
      "You grant us a limited license to process your data solely to provide the service",
    ],
  },
  {
    icon: Link2,
    title: "6. Third-Party Integrations",
    content: "ARIA connects to third-party services (Gmail, X/Twitter, LinkedIn, WhatsApp, etc.) on your behalf. By connecting these services:",
    items: [
      "You authorize ARIA to perform actions on your behalf (send emails, publish posts, etc.)",
      "You agree to comply with each third-party platform's terms of service",
      "ARIA is not responsible for changes to third-party APIs or terms",
      "You can disconnect any integration at any time from Settings",
      "All actions requiring external publishing require your explicit approval before execution",
    ],
  },
  {
    icon: CheckCircle,
    title: "7. Approval and Confirmation",
    content: "ARIA implements a mandatory approval system for critical actions:",
    items: [
      "Emails are never sent without your explicit approval",
      "Social media posts are never published without your explicit approval",
      "Data modifications (updates, deletions) require confirmation",
      "You may review, edit, or cancel any pending action before it executes",
    ],
    highlight: true,
  },
  {
    icon: CreditCard,
    title: "8. Subscription and Payments",
    items: [
      "ARIA may offer subscription plans with different feature tiers in the future",
      "If and when paid plans are introduced, payments will be processed by a PCI-compliant third-party payment processor (e.g. Stripe); ARIA does not store full credit card numbers",
      "Subscription terms, renewal, cancellation, and refund policies will be presented at the point of purchase",
      "We reserve the right to change pricing with 30 days' notice to active subscribers",
      "During the current early-access / waitlist period, the Platform may be provided free of charge while we collect feedback",
    ],
  },
  {
    icon: Lock,
    title: "9. Data and Privacy",
    content: "Your use of ARIA is also governed by our Privacy Policy, which describes how we collect, use, and protect your information.",
    link: { label: "Read our Privacy Policy", href: "/privacy" },
  },
  {
    icon: Scale,
    title: "10. Intellectual Property",
    items: [
      "The ARIA platform, including its design, code, AI models, and documentation, is owned by us",
      "Your business data, content, and marketing materials remain yours",
      "You grant us a non-exclusive license to use your data to provide and improve the service",
      "We do not use your data to train AI models for other customers",
    ],
  },
  {
    icon: Server,
    title: "11. Service Availability",
    items: [
      "We strive to maintain high availability but do not guarantee uninterrupted service",
      "We may perform maintenance with reasonable notice",
      "We are not liable for downtime caused by third-party service outages",
      "AI agent performance depends on third-party AI providers (Anthropic Claude)",
    ],
  },
  {
    icon: AlertTriangle,
    title: "12. Limitation of Liability",
    content: "To the maximum extent permitted by law, ARIA and its operators shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including but not limited to loss of profits, data, business opportunities, or goodwill.\n\nOur total liability for any claims arising from your use of ARIA shall not exceed the amount you paid us in the twelve (12) months preceding the claim.",
  },
  {
    icon: AlertTriangle,
    title: "13. Disclaimer of Warranties",
    content: 'ARIA is provided "as is" and "as available" without warranties of any kind, either express or implied, including but not limited to implied warranties of merchantability, fitness for a particular purpose, or non-infringement. We do not warrant that AI-generated content will be error-free, effective, or suitable for your specific marketing needs.',
  },
  {
    icon: XCircle,
    title: "14. Termination",
    items: [
      "You may close your account at any time",
      "We may suspend or terminate your account for violation of these Terms",
      "Upon termination, your right to use the Platform ceases immediately",
      "We will retain your data for 30 days after termination, after which it will be deleted",
    ],
  },
  {
    icon: Bell,
    title: "15. Changes to Terms",
    content: 'We may modify these Terms at any time. We will notify you of material changes by posting the updated Terms on this page and updating the "Last updated" date. Continued use of the Platform after changes constitutes acceptance of the modified Terms.',
  },
  {
    icon: Gavel,
    title: "16. Governing Law",
    content: "These Terms shall be governed by and construed in accordance with applicable laws, without regard to conflict of law principles.",
  },
  {
    icon: Mail,
    title: "17. Contact Us",
    content: "If you have questions about these Terms of Service, please contact us at:",
    contact: "accounts@zillamedia.co",
  },
];

export default function TermsOfServicePage() {
  return (
    <div className="min-h-screen bg-gradient-to-b from-[#F8F8F6] to-white">
      {/* Hero */}
      <div className="bg-[#2C2C2A] text-white py-20">
        <div className="max-w-3xl mx-auto px-6 text-center">
          <div className="w-14 h-14 rounded-2xl bg-[#534AB7] flex items-center justify-center mx-auto mb-6">
            <FileText className="w-7 h-7 text-white" />
          </div>
          <h1 className="text-4xl font-bold mb-3">Terms of Service</h1>
          <p className="text-[#9E9C95] text-sm">Last updated: May 6, 2026</p>
        </div>
      </div>

      {/* Content */}
      <div className="max-w-3xl mx-auto px-6 py-12 space-y-6">
        {sections.map((section) => {
          const Icon = section.icon;
          return (
            <div
              key={section.title}
              className={`bg-white rounded-xl border p-6 shadow-sm ${
                section.highlight ? "border-[#534AB7] ring-1 ring-[#534AB7]/10" : "border-[#E0DED8]"
              }`}
            >
              <div className="flex items-start gap-3 mb-4">
                <div className={`w-9 h-9 rounded-lg flex items-center justify-center flex-shrink-0 mt-0.5 ${
                  section.highlight ? "bg-[#534AB7] text-white" : "bg-[#EEEDFE]"
                }`}>
                  <Icon className={`w-4.5 h-4.5 ${section.highlight ? "text-white" : "text-[#534AB7]"}`} />
                </div>
                <h2 className="text-lg font-semibold text-[#2C2C2A]">{section.title}</h2>
              </div>

              {section.content && (
                <p className="text-sm text-[#5F5E5A] leading-relaxed whitespace-pre-line ml-12">{section.content}</p>
              )}

              {section.items && (
                <ul className="ml-12 mt-3 space-y-1.5">
                  {section.items.map((item) => (
                    <li key={item} className="text-sm text-[#5F5E5A] flex items-start gap-2">
                      <span className={`w-1.5 h-1.5 rounded-full mt-1.5 flex-shrink-0 ${
                        section.highlight ? "bg-[#534AB7]" : "bg-[#9E9C95]"
                      }`} />
                      {item}
                    </li>
                  ))}
                </ul>
              )}

              {section.link && (
                <div className="ml-12 mt-3">
                  <a href={section.link.href} className="inline-flex items-center gap-1.5 text-sm font-medium text-[#534AB7] hover:underline">
                    {section.link.label}
                    <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" strokeWidth={2} viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" d="M13.5 6H5.25A2.25 2.25 0 003 8.25v10.5A2.25 2.25 0 005.25 21h10.5A2.25 2.25 0 0018 18.75V10.5m-10.5 6L21 3m0 0h-5.25M21 3v5.25" />
                    </svg>
                  </a>
                </div>
              )}

              {section.contact && (
                <p className="ml-12 mt-2 text-sm font-medium text-[#534AB7]">{section.contact}</p>
              )}
            </div>
          );
        })}
      </div>
    </div>
  );
}
