export default function TermsOfServicePage() {
  return (
    <div className="py-16">
      <div className="max-w-3xl mx-auto px-6">
        <h1 className="text-3xl font-bold text-[#2C2C2A] mb-2">Terms of Service</h1>
        <p className="text-sm text-[#9E9C95] mb-8">Last updated: April 1, 2026</p>

        <div className="prose prose-sm max-w-none text-[#5F5E5A] space-y-6">
          <section>
            <h2 className="text-lg font-semibold text-[#2C2C2A]">1. Acceptance of Terms</h2>
            <p>
              By accessing or using ARIA (&quot;the Platform&quot;), you agree to be bound by these Terms of Service
              (&quot;Terms&quot;). If you do not agree to these Terms, do not use the Platform.
              ARIA is operated by ARIA Technologies (&quot;we&quot;, &quot;our&quot;, &quot;us&quot;).
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-[#2C2C2A]">2. Description of Service</h2>
            <p>
              ARIA is an AI-powered marketing platform that provides developer founders with autonomous
              AI agents for content creation, email marketing, social media management, and advertising strategy.
              The platform generates marketing content, manages campaigns, and executes approved marketing
              actions on your behalf through connected third-party services.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-[#2C2C2A]">3. Account Registration</h2>
            <ul className="list-disc pl-5 space-y-1">
              <li>You must provide accurate and complete information when creating an account</li>
              <li>You are responsible for maintaining the confidentiality of your account credentials</li>
              <li>You are responsible for all activities that occur under your account</li>
              <li>You must be at least 18 years old to use ARIA</li>
              <li>One person or legal entity may not maintain more than one account</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-[#2C2C2A]">4. Acceptable Use</h2>
            <p>You agree not to use ARIA to:</p>
            <ul className="list-disc pl-5 space-y-1">
              <li>Generate spam, misleading, or fraudulent content</li>
              <li>Violate any applicable laws or regulations</li>
              <li>Infringe on intellectual property rights of others</li>
              <li>Harass, abuse, or harm other individuals</li>
              <li>Distribute malware or engage in phishing</li>
              <li>Attempt to gain unauthorized access to the Platform or other users&apos; accounts</li>
              <li>Use the Platform for illegal marketing practices</li>
              <li>Scrape, crawl, or use automated means to access the Platform beyond the provided API</li>
              <li>Reverse engineer or attempt to extract source code from the Platform</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-[#2C2C2A]">5. AI-Generated Content</h2>
            <ul className="list-disc pl-5 space-y-1">
              <li>Content generated by ARIA&apos;s AI agents is provided as suggestions and drafts</li>
              <li>You are responsible for reviewing all generated content before publishing or sending</li>
              <li>ARIA does not guarantee the accuracy, quality, or appropriateness of AI-generated content</li>
              <li>You retain ownership of content generated for your business, subject to our license below</li>
              <li>We do not claim ownership of your business data, generated content, or marketing materials</li>
              <li>You grant us a limited license to process your data solely to provide the service</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-[#2C2C2A]">6. Third-Party Integrations</h2>
            <p>
              ARIA connects to third-party services (Gmail, X/Twitter, LinkedIn, WhatsApp, etc.)
              on your behalf. By connecting these services:
            </p>
            <ul className="list-disc pl-5 space-y-1">
              <li>You authorize ARIA to perform actions on your behalf (send emails, publish posts, etc.)</li>
              <li>You agree to comply with each third-party platform&apos;s terms of service</li>
              <li>ARIA is not responsible for changes to third-party APIs or terms</li>
              <li>You can disconnect any integration at any time from Settings</li>
              <li>All actions requiring external publishing require your explicit approval before execution</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-[#2C2C2A]">7. Approval and Confirmation</h2>
            <p>
              ARIA implements a mandatory approval system for critical actions:
            </p>
            <ul className="list-disc pl-5 space-y-1">
              <li>Emails are never sent without your explicit approval</li>
              <li>Social media posts are never published without your explicit approval</li>
              <li>Data modifications (updates, deletions) require confirmation</li>
              <li>You may review, edit, or cancel any pending action before it executes</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-[#2C2C2A]">8. Subscription and Payments</h2>
            <ul className="list-disc pl-5 space-y-1">
              <li>ARIA offers subscription plans with different feature tiers</li>
              <li>Payments are processed securely through Stripe</li>
              <li>Subscriptions renew automatically unless cancelled</li>
              <li>You may cancel your subscription at any time; access continues until the end of the billing period</li>
              <li>Refunds are handled on a case-by-case basis</li>
              <li>We reserve the right to change pricing with 30 days&apos; notice</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-[#2C2C2A]">9. Data and Privacy</h2>
            <p>
              Your use of ARIA is also governed by our{" "}
              <a href="/privacy" className="text-[#534AB7] hover:underline">Privacy Policy</a>,
              which describes how we collect, use, and protect your information.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-[#2C2C2A]">10. Intellectual Property</h2>
            <ul className="list-disc pl-5 space-y-1">
              <li>The ARIA platform, including its design, code, AI models, and documentation, is owned by us</li>
              <li>Your business data, content, and marketing materials remain yours</li>
              <li>You grant us a non-exclusive license to use your data to provide and improve the service</li>
              <li>We do not use your data to train AI models for other customers</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-[#2C2C2A]">11. Service Availability</h2>
            <ul className="list-disc pl-5 space-y-1">
              <li>We strive to maintain high availability but do not guarantee uninterrupted service</li>
              <li>We may perform maintenance with reasonable notice</li>
              <li>We are not liable for downtime caused by third-party service outages</li>
              <li>AI agent performance depends on third-party AI providers (Anthropic Claude)</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-[#2C2C2A]">12. Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by law, ARIA and its operators shall not be liable for any
              indirect, incidental, special, consequential, or punitive damages, including but not limited to
              loss of profits, data, business opportunities, or goodwill, arising out of or related to your
              use of the Platform.
            </p>
            <p>
              Our total liability for any claims arising from your use of ARIA shall not exceed the amount
              you paid us in the twelve (12) months preceding the claim.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-[#2C2C2A]">13. Disclaimer of Warranties</h2>
            <p>
              ARIA is provided &quot;as is&quot; and &quot;as available&quot; without warranties of any kind,
              either express or implied, including but not limited to implied warranties of merchantability,
              fitness for a particular purpose, or non-infringement. We do not warrant that AI-generated
              content will be error-free, effective, or suitable for your specific marketing needs.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-[#2C2C2A]">14. Termination</h2>
            <ul className="list-disc pl-5 space-y-1">
              <li>You may close your account at any time</li>
              <li>We may suspend or terminate your account for violation of these Terms</li>
              <li>Upon termination, your right to use the Platform ceases immediately</li>
              <li>We will retain your data for 30 days after termination, after which it will be deleted</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-[#2C2C2A]">15. Changes to Terms</h2>
            <p>
              We may modify these Terms at any time. We will notify you of material changes by posting
              the updated Terms on this page and updating the &quot;Last updated&quot; date. Continued use of
              the Platform after changes constitutes acceptance of the modified Terms.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-[#2C2C2A]">16. Governing Law</h2>
            <p>
              These Terms shall be governed by and construed in accordance with applicable laws,
              without regard to conflict of law principles.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-[#2C2C2A]">17. Contact Us</h2>
            <p>
              If you have questions about these Terms of Service, please contact us at:
            </p>
            <p className="font-medium text-[#2C2C2A]">
              Email: support@aria.ai
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
